# Generated by Django 5.0 on 2024-05-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('iban', models.CharField(max_length=24, unique=True)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('balance', models.FloatField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('cards', models.ManyToManyField(to='proj_backend.card')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('cards', models.ManyToManyField(to='proj_backend.card')),
            ],
        ),
        migrations.CreateModel(
            name='ProducerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('cards', models.ManyToManyField(to='proj_backend.card')),
            ],
        ),
    ]
