# Generated by Django 5.0.4 on 2024-05-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_backend', '0002_userdata_delete_normaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='type',
            field=models.CharField(default='normal', max_length=100),
        ),
    ]
